services:
  - type: web
    name: pehchan-webapp
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    releaseCommand: "python manage.py migrate && python manage.py create_admin_user"
    startCommand: gunicorn pehchan_webapp.wsgi:application --workers 2 --threads 2 --worker-class gthread
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pehchan-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: pehchan_webapp.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ""
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        value: admin@pehchanyui.in
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 2

databases:
  - name: pehchan-db
    plan: free
