# Generated by Django 6.0.6 on 2026-07-17 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pehchan', '0009_remove_lifetimevolunteer_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousdonation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donorcertificate',
            name='issue_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], db_index=True, default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventvolunteer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lifetimevolunteer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialdonation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='materialdonation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('processed', 'Processed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='moneydonation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='moneydonation',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('declined', 'Declined')], db_index=True, default='unverified', max_length=20),
        ),
    ]
